# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

'$schema' = 'https://reuse.software/reuse-toml-v1.schema.json'
version = 1

[[annotations]]
SPDX-FileCopyrightText = 'NONE'
SPDX-License-Identifier = 'CC0-1.0'
path = ['nix/dev/flake.lock', '.envrc', 'flake.lock']
precedence = 'aggregate'

[[annotations]]
SPDX-FileCopyrightText = 'NONE'
SPDX-License-Identifier = 'CC-BY-4.0'
path = ['CONTRIBUTING.md', 'README.md']
precedence = 'aggregate'

[[annotations]]
SPDX-FileCopyrightText = '2019 Hercules Labs OÜ'
SPDX-License-Identifier = 'Apache-2.0'
path = ['.pre-commit-config.yaml']
precedence = 'override'

[[annotations]]
SPDX-FileCopyrightText = ['2026 Organization for Ethical Source <info@ethicalsource.dev>', 'NONE']
SPDX-License-Identifier = 'CC-BY-SA-4.0'
path = ['.github/CODE_OF_CONDUCT.md']
precedence = 'override'